/// Sinistres de sev absents de freq. Table indépendante, non filtrée par les caractéristiques des contrats.
table Orphelins
	lineageTag: 290c4d2e-030f-5875-85f9-1e6d0fe624cb

	column LigneSource
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: bb75efb2-7013-5bb7-94cd-2aadf0db4191
		summarizeBy: none
		sourceColumn: LigneSource

	column IDpol
		dataType: int64
		formatString: #,0
		lineageTag: b04559bf-32ac-50e0-91d8-1cccfc2ab479
		summarizeBy: none
		sourceColumn: IDpol

	column ClaimAmount
		dataType: double
		formatString: #,0.00
		lineageTag: 96ae3333-3d45-5d99-8e4c-a03b95e66bd4
		summarizeBy: none
		sourceColumn: ClaimAmount

	partition Orphelins = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DossierDonnees & "\orphelins.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Types = Table.TransformColumnTypes(Entetes, {{"LigneSource", Int64.Type}, {"IDpol", Int64.Type}, {"ClaimAmount", type number}}, "en-US")
				in
				    Types
