/// Une ligne par sinistre observé de sev rapproché. Montants incomplets ; répétitions conservées.
table Sinistres
	lineageTag: 2f47de73-3942-5f2a-ab62-641b9cf790cc

	column LigneSource
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 5967a2df-826f-54a6-832d-203abe78e5c8
		summarizeBy: none
		sourceColumn: LigneSource

	column IDpol
		dataType: int64
		formatString: #,0
		lineageTag: 75e036a9-94a1-5ada-a5b3-173da1164668
		summarizeBy: none
		sourceColumn: IDpol

	column ClaimAmount
		dataType: double
		formatString: #,0.00
		lineageTag: dc0d4f71-99d2-530c-8c88-756778d5cd3e
		summarizeBy: none
		sourceColumn: ClaimAmount

	partition Sinistres = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DossierDonnees & "\sinistres.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Types = Table.TransformColumnTypes(Entetes, {{"LigneSource", Int64.Type}, {"IDpol", Int64.Type}, {"ClaimAmount", type number}}, "en-US")
				in
				    Types
